name: Upload Invoice to GitHub

on:
  push:
    paths:
      - 'فاکتور/*'   # واکنش به تغییرات در پوشه فاکتور

jobs:
  upload_invoice:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Move Invoice to فاکتور
        run: |
          mv home.html فاکتور/home.html  # انتقال فایل فاکتور به پوشه فاکتور

      - name: Commit and Push Invoice
        run: |
          git add فاکتور/home.html
          git commit -m "Add new invoice"
          git push
